### ISSUE TITLE
error: private method `to_date' called

### ISSUE THREAD

**Issue by sogrady** [stefan-pdx/mlb_terminal#2]
$ mlb games 
error: private method `to_date' called for Sun Oct 07 13:13:15 -0400 2012:Time. Use --trace to view backtrace

And the trace;

$ mlb games --trace
/Library/Ruby/Gems/1.8/gems/mlb_terminal-0.0.4/bin/mlb:19: private method `to_date' called for Sun Oct 07 13:13:19 -0400 2012:Time (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.2/lib/commander/command.rb:180:in`call'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.2/lib/commander/command.rb:180:in `call'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.2/lib/commander/command.rb:155:in`run'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.2/lib/commander/runner.rb:402:in `run_active_command'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.2/lib/commander/runner.rb:78:in`run!'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.2/lib/commander/delegates.rb:7:in `run!'
    from /Library/Ruby/Gems/1.8/gems/commander-4.1.2/lib/commander/import.rb:10
    from /usr/bin/mlb:19

**Comment by stefan-pdx** [comment]
Thanks for pointing this out! I'll be addressing this issue in the next release which uses the Chronic gem for handling date parsing.

**Comment by stefan-pdx** [comment]
sogrady, it looks like that's an issue with the `date` module in 1.8.7. Can you use Ruby 1.9.3?

```
➜  ~  mlb games                                                                                                                                                                                                                                                                                                                                                   
error: private method `to_date' called for Mon Oct 08 16:25:48 -0400 2012:Time. Use --trace to view backtrace
➜  ~  rvm 1.9.3                                                                                                                                                                                                                                                                                                                                               
➜  ~  mlb games                                                                                                                                                                                                                                                                                                                                               
0   Nationals (1-0) @ Cardinals (0-1)   4:30 ET (Warmup)    0-0
1   Yankees (1-0) @ Orioles (0-1)   8:00 ET (Preview)   -
```

**Comment by sogrady** [comment]
Problem solved. Thanks for the super quick turn around, and great work on this app. 

If only Baseball Reference or Fangraphs had an API and a client like this.

**Comment by stefan-pdx** [comment]
Just to follow up! I added the dependency in the gemspec to only allow the use of this gem with Ruby 1.9+. I also added date parsing with the Chronic gem, so you can say things like `mlb games --date "4 days ago"`.

Thanks again!
